import { type AppType } from "next/app";
import Head from 'next/head';
import { api } from "../util/api";
import "../styles/globals.css";

const MyApp: AppType = ({
  Component,
  pageProps,
}) => {
  return (<>
	<Head>
		<title>Create T3 App</title>
		<meta content="Generated by create-t3-app" name="description" />
		<link href="/favicon.ico" rel="icon" />
	</Head>
	<main className="flex min-h-screen flex-col">
		<Component {...pageProps} />
	</main>
	</>
  );
};

export default api.withTRPC(MyApp);