import { type Session } from "next-auth";
import { SessionProvider } from "next-auth/react";
import { type AppType } from "next/app";
import { api } from "~/utils/api";
import Head from 'next/head';
import {SideNav} from '~/utils/components/navigation/sidenav';
import "~/styles/globals.css";
import { Navbar } from "~/utils/components/navigation/navbar";

const MyApp: AppType<{ session: Session | null }> = ({
  Component,
  pageProps: { session, ...pageProps },
}) => {
  return (
    <SessionProvider session={session}>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col">
        <Navbar/>
        <SideNav className="pt-20">
          <Component {...pageProps} />
        </SideNav>
      </main>
    </SessionProvider>
  );
};

export default api.withTRPC(MyApp);
